name: MLOps Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test-train-evaluate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Preprocessing
        run: |
          python src/preprocess.py

      - name: Run Unit Testing
        run: |
          pytest

      - name: Train Model
        run: |
          python src/train.py

      - name: Evaluation Success
        run: |
          echo "Model berhasil dilatih dan lolos evaluasi"